### ISSUE TITLE
Durability issue

### ISSUE THREAD

**Issue by vertex101** [jonahisadev/TreeMe#1]
when your tool runs out of durability it just keeps going into the negative and doesnt break

**Comment by jonahisadev** [comment]
Thanks for bringing this to my attention. I'm on vacation, but if I find some free time I can get this taken care of.

**Comment by jonahisadev** [comment]
Fixed this with my [latest commit](https://github.com/jonahisadev/TreeMe/commit/f62bb3253f18482b88e5e6b0f991243afe8c89e7)
