### ISSUE TITLE
Jungle Trees not Dropping Sapplings

### ISSUE THREAD

**Issue by ReallyBees** [jonahisadev/TreeMe#8]
It seems that while using Treeme, for me at least, the saplings don't seem to want to drop.

I tried turning replanting off, but it doesn't seem to affect anything.

**Comment by jonahisadev** [comment]
This could be an issue with a recent pull request. I'll take a look. Should be simple!

**Comment by jonahisadev** [comment]
Is this specific to jungle trees or is this happening for all trees?

**Comment by ErrorMeister** [comment]
I believe #7 may have fixed this issue although those changes don't appear to have been pushed to a release. I apologize in advance if I comment isn't all that great as I'm new to this whole GitHub and software development thing.

**Comment by ghost** [comment]
I believe #7 fixed this issue if it is limited to jungle trees. These changes don't appear to have been pushed to a release though.

**Comment by jonahisadev** [comment]
You are right, I will build and release the updates tomorrow

**Comment by jonahisadev** [comment]
Just released a version that has this fix
