### ISSUE TITLE
Jar seems Excessively Large

### ISSUE THREAD

**Issue by ghost** [jonahisadev/TreeMe#9]
This plugin's jar seems excessively large compared to other similar plugins some of which seem more complex.

On both Github Releases and CurseForge, the TreeMe jar is 1.27 MB.

One popular treecapitator-esque plugin known as Cristichi's Tree Capitator is 67.90 KB
Sources: https://github.com/Cristichi/CrisTreeCapitator , https://www.curseforge.com/minecraft/bukkit-plugins/cristichis-tree-capitator

Another popular treecapitator-esque plugin known as Timber Plugin is 4.25 KB.
Sources: https://github.com/Aurilisdev/Timber , https://www.curseforge.com/minecraft/bukkit-plugins/timber-plugin

I appreciate any clarification you can provide, and I hope I am not unduly wasting your time.

**Comment by jonahisadev** [comment]
You are not wasting my time at all. TreeMe, though a hobby project, is something that I want to be helpful for others. If the size of the plugin is something you see as an issue, then I'm more than willing to look into how I can cut down on the jar size. It does seem odd that it's significantly larger than other related projects, by an order of magnitude no less.

I'll see if I'm linking the spigot/paper library incorrectly. Thanks for bringing this to my attention!

**Comment by jonahisadev** [comment]
Just released the fix for this!
